/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task05peoplenet;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MrSkud
 */
public class People extends javax.swing.JFrame {

    /**
     * Creates new form People
     */
    static final String FILE_NAME = "person.txt";

    public People() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgeRange = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAge18 = new javax.swing.JRadioButton();
        btnAge35 = new javax.swing.JRadioButton();
        btnAgeUp = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cbPetCat = new javax.swing.JCheckBox();
        cbPetDog = new javax.swing.JCheckBox();
        cbPetOther = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        dbContinent = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sTemp = new javax.swing.JSlider();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Information");
        setResizable(false);

        jLabel1.setText("Name:");

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Age:");

        btnAgeRange.add(btnAge18);
        btnAge18.setText("below 18");

        btnAgeRange.add(btnAge35);
        btnAge35.setText("18-35");

        btnAgeRange.add(btnAgeUp);
        btnAgeUp.setText("36 and up");

        jLabel3.setText("Pets:");

        cbPetCat.setText("Cat");

        cbPetDog.setText("Dog");

        cbPetOther.setText("Other");

        jLabel4.setText("Continent of residence");

        dbContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North America", "South America", "Antarctica", "Europe", "Asia", "Africa", "Australia" }));

        jLabel5.setText("Preferred temp C");

        sTemp.setMaximum(35);
        sTemp.setMinimum(15);
        sTemp.setValue(25);

        btnRegister.setText("Register Me!");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPetCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPetDog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPetOther))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(sTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dbContinent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAge18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAge35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAgeUp))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnAge18)
                    .addComponent(btnAge35)
                    .addComponent(btnAgeUp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPetCat)
                    .addComponent(cbPetDog)
                    .addComponent(cbPetOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dbContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(sTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed

    }//GEN-LAST:event_tfNameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        try (FileWriter fw = new FileWriter(FILE_NAME, true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter out = new PrintWriter(bw)) {
            out.println(String.format("%s;%s;%s;%s;%d", inputName(), btnChoice(), petChoice(), dbContinent.getSelectedItem().toString(), sTemp.getValue()));

        } catch (IOException ex) {
            System.out.println("File not found");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Input error",
                    JOptionPane.ERROR_MESSAGE);
        }
        tfName.setText("");
        btnAgeRange.clearSelection();
        cbPetCat.setSelected(false);
        cbPetDog.setSelected(false);
        cbPetOther.setSelected(false);
        dbContinent.setSelectedIndex(0);
        sTemp.setValue(25);

    }//GEN-LAST:event_btnRegisterActionPerformed

    public String petChoice() {
        String res = "";
        if (cbPetCat.isSelected() && cbPetDog.isSelected() && cbPetOther.isSelected()) {
            res = "Cat,Dog,Other";
        } else if (cbPetCat.isSelected() && cbPetDog.isSelected()) {
            res = "Cat,Dog";
        } else if (cbPetCat.isSelected() && cbPetOther.isSelected()) {
            res = "Cat,Other";
        } else if (cbPetDog.isSelected() && cbPetOther.isSelected()) {
            res = "Dog,Other";
        } else if (cbPetDog.isSelected()) {
            res = "Dog";
        } else if (cbPetCat.isSelected()) {
            res = "Cat";
        } else if (cbPetOther.isSelected()) {
            res = "Other";
        } else {
            res = "No Pet";
        }
        return res;
    }

    public String btnChoice() throws IOException {
        String res;

        if (btnAge18.isSelected() == true) {
            res = btnAge18.getText();
        } else if (btnAge35.isSelected() == true) {
            res = btnAge35.getText();
        } else if (btnAgeUp.isSelected() == true) {
            res = btnAgeUp.getText();
        } else {
            res = "";
        }

        return res;
    }

    String inputName() throws ParseException {
        String name = tfName.getText();
        if (name.length() < 2 || name.length() > 30) {
            throw new ParseException("Name must be 2-30 character long", 0);
        }
        return name;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(People.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(People.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(People.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(People.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new People().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAge18;
    private javax.swing.JRadioButton btnAge35;
    private javax.swing.ButtonGroup btnAgeRange;
    private javax.swing.JRadioButton btnAgeUp;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox cbPetCat;
    private javax.swing.JCheckBox cbPetDog;
    private javax.swing.JCheckBox cbPetOther;
    private javax.swing.JComboBox<String> dbContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSlider sTemp;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
